SCR_PlaceableEntitiesRegistry {
 m_sAddon "ConvoyFollower"
 m_sSourceDirectory "Prefabs/Groups"
 m_bExposed 1
 m_Prefabs {
  "{949579FDD2398E3C}Prefabs/Groups/Group_CF_Driver.et"
  "{18A8FAF9C3034738}Prefabs/Groups/Group_CF_Driver_USSR.et"
 }
}
